sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t mariusb/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true mariusb/frontend npm run test -- --coverage
